Repository CA-G12/library-app, pull requests merged in 2022-08, with the labels that each got.

#3 2 creating file structure
  .eslintrc.json
  .gitignore
  .gitkeep
  package-lock.json
  package.json
  public/css/style.css
  public/index.html
  public/js/index.js
  src/app.js
  src/controllers/index.js
  src/database/config/build.js
  src/database/config/build.sql
  src/database/config/connections.js
  src/database/queries/getData.js
  src/database/queries/postData.js
  src/index.js
  src/routes/index.js
Labels: awaiting review

#5 create the server and the folder test
  __test__/test.js
  package-lock.json
  package.json
  src/app.js
  src/index.js
Labels: awaiting review

#7 creating tables
  src/database/config/build.sql
Labels: awaiting review

#10 fix the bugs in database
  src/database/config/build.sql
Labels: approved

#11 8 creating styling
  public/css/style.css
  public/index.html
Labels: awaiting review

#14 13 creaing styling errors
  public/css/errors.css
  public/html/404.html
  public/html/500.html
Labels: awaiting review

#18 create render function
  .vscode/settings.json
  public/js/index.js
  src/app.js
  src/controllers/index.js
  src/index.js
Labels: approved

#20 16 create adding book form
  public/css/form.css
  public/html/500.html
  public/html/addBook.html
Labels: awaiting review

#21 fixed start script and db name
  package.json
  src/database/config/connections.js
Labels: bug, awaiting review

#25 added readme
  README.md
Labels: documentation, awaiting review
